[brain]
iointel_key = ""

[rag]
qdrant_api = "https://5915f2b6-260a-485b-b2b3-b50ce2c3628d.us-west-1-0.aws.cloud.qdrant.io"
qdrant_api_key = ""

[langfuse]
secret_key=""
public_key=""


[clickhouse]
api_key = ""